### ISSUE TITLE
Is there any community forum/space? I want to join as developer/QA

### ISSUE THREAD

**Issue by MaciejKmon** [dtinit/data-transfer-project#1248]
Hello 
My name is Maciej and I am a software developer, with 6 years of commercial experience.
For my entire career I worked on proprietary/closed base software, and I would like to have some code/tests I wrote I can show others.

BEFORE I START - I AM A PERSON WHO ASKS FOR HELP ONLY WHEN I CANNOT DO SOMETHING MYSELF AND ALREADY TRIED.
The thing is - I browsed through hundreds of repositories and came to conclusion that nearly EVERYONE (I mean numbers wise) on Github/Gitlab etc. starts THEIR OWNE NEW project FOR THEMSELVES/ON THEIR OWN and its pretty much standard procedure.
Then they are the BOSS, they control everything, its surely FEELS GOOD for them, but in my humble opinion its irrational. There is no one to give them CR and once they decide either that they no longer care (a lot of developers unfortunately love to start something and then leave it as they please at their whim) they won't even DESCRIBE in readme.md in which state they abandoned it (complete, MVP, 30% complete - not even that). Not to mension that even if there is a description usually its written in a way that only people who are in some extreme niche (like a build planner for specific mmorpg game that 100 people plays) without even containing information what is the niche name. Its free for all ,,whatever author likes even if he don't know what he/she likes".

Therefore there is a lot of abandoned repositories is shitty state on Github, I already checked few hundreds of them. 

But I have to do this since at the beginning I just picked a repository I liked that seem not abandoned (commits this year), there was some instructions how to get started... So I did. And then I needed more information. Test Data, Information WHAT PROGRAM ACTUALLY DOES/HOW DO YOU USE THIS (you would be surprised how many devs do not care to include it. It is scary how majority of Github projects look like someones summer hut abandoned for the rest of the year). 

I am tired of this. What I look for is a project WITH COMMUNITY. I want to dedicate at least 10h per month to this project either writing some features (I like this least), fixing some bugs (This is what I like the most. Seriously I prefer to edit existing code than writing a new one) or writing autormation Tests with Selenium. 

But I need there 2 things from community that (and IF, ok?) would be willing to accept my free labor

- HAND HOLDING - YES! Especially in the beginning. And I do not mean to tell me what code to write ALL THE TIME. But I expect some instructions and help if I am stuck for too long when setting up dev environment for example on Docker, Code Review - and If my code displeases you, I expect you to tell me HOW to do it better and then review my attempt. I am more than willing to do the same FOR YOUR CODE.
- To not throw me out - Yes, If my code/way of thinking/level of expertise will turn out to be not enough to your taste, I expect for you to tell me where to find materials, then I go there, study, get better. What I do not want is to join a community that only accepts dev with JOB-READY skills and If I show any struggle - community choses easy and lazy way and just tell me to go away AFTER accepting me before. If you have any doubt about me - show me to the door NOW instead of when I spend 30hrs getting started and invested just to be thrown out because you did not care cause its not you who has the problem. You can thrown me out if I am ahole to other people or if I try to monetize/rip you off - because I KNOW THIS IS NOT GOING TO HAPPEN.
In other words, I would like to join a project and give you value, but with these 2 requirements. I am sorry if I came off as rude, but I already spend many hours in my life doing something for someone just to be told after I invested over 40hrs that they actually are not interested and I can go fk myself. I do not want to waste my time. And I assume you are awesome people but in any place where someone don't need to pay for others time there are lurking smug and selfish idividuals and those are the one I wish to avoid. 
Do not get me wrong - I WANT TO CONTRIBUTE, FOR FREE, REGULARLY and this will not change. I just want a community to accomodate me or tell me to go away.

If your community can do just that, I would like to join. Please tell me what to do, or how to find what to do by myself in a way that is beneficial to the project.

But I want to know whether there is any space where I CAN TALK TO THE TEAM of contributors. Without it I cannot join, I won't join people I cannot reach.

**Comment by NawazTalha** [comment]
I would like to connect with you. I am a newbie and seeking for help

**Comment by donphelix** [comment]
Hi @MaciejKmon,

Dive into groups where you can thrive and make your mark. Being part of a community makes a difference, even if it's a challenge at first. Choose projects you're passionate about, begin with ``good first issue`` tasks, and progress steadily. Remember, growth happens faster when you're not alone on the journey. Best of luck! 🌟

**Comment by lisad** [comment]
DTP does not presently have an open community forum.
