### ISSUE TITLE
Build out Google service unit tests

### ISSUE THREAD

**Issue by olsona** [dtinit/data-transfer-project#170]
Google services need unit tests.

**Comment by olsona** [comment]
#5

**Comment by r-pawar** [comment]
I would like to contribute to this issue. Please let me know details.

**Comment by Swikar** [comment]
anyone here help me out with more detail? I know its long time

**Comment by Swikar** [comment]
/ assign

**Comment by anand007s** [comment]
please assign it to me....

**Comment by HKMANOJ** [comment]
hi i want to contribute to this issue

**Comment by vimalJD** [comment]
### **Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".**

**Comment by calumcalder** [comment]
There are significantly more unit tests for Google extensions than in 2018 when this issue was created, so closing as completed.
