### ISSUE TITLE
IntelliJ reports error with duplicate AutoValue generated classes

### ISSUE THREAD

**Issue by holachuy** [dtinit/data-transfer-project#173]
Run ./gradle clean build
Run IntelliJ - build/rebuild project 

Error:(9, 8) java: duplicate class: org.dataportabilityproject.spi.cloud.types.AutoValue_LegacyPortabilityJob
Error:(9, 8) java: duplicate class: org.dataportabilityproject.spi.cloud.types.AutoValue_JobAuthorization
Error:(9, 8) java: duplicate class: org.dataportabilityproject.spi.cloud.types.AutoValue_PortabilityJob

Work around is to run ./gradlew clean  (not build) before IntelliJ build or tests

**Comment by LeshaRB** [comment]
I have such problem

```
/media/lesharb/Data/Workspace/github/mongo-utils/mongo-info/out/production/classes/generated/by/lesharb/mongo/info/data/AutoValue_HostInfo.java
Error:(9, 8) java: duplicate class: by.lesharb.mongo.info.data.AutoValue_HostInfo
```

**Comment by lisad** [comment]
Probably obsolete - chuy can reopen if we want to identify some work that we can prioritize in folks roadmaps!
