### ISSUE TITLE
Checked or Unchecked exceptions

### ISSUE THREAD

**Issue by jimmarino** [dtinit/data-transfer-project#176]
The issue of checked vs. unchecked exceptions has been raised on Slack. Based on the outcome of that discussion, changes will need to be made to harmonize the codebase.

**Comment by rtannenbaum** [comment]
Jim's comment from PR #167 about this:

"I would argue for unchecked exceptions except in cases where it is absolutely necessary to signal a condition is recoverable. Runtime exceptions can bubble up to the top of the stack where they can be trapped and logged. "
