### ISSUE TITLE
Add support for Shutterfly

### ISSUE THREAD

**Issue by bwillard** [dtinit/data-transfer-project#23]
https://www.shutterfly.com/documentation/start.sfly

**Comment by Gairick52** [comment]
@olsona do you need any help on this issue,i am beginner will more than willing to contribute

**Comment by Moo331** [comment]
Yes

**Comment by Gairick52** [comment]
@Moo331 `let me know if you need any help  needed

**Comment by Moo331** [comment]
I need help

**Comment by darvesh29** [comment]
> I need help

how can i help you

**Comment by rohitchouhan35** [comment]
@Moo331 I'm a beginner and ready to burn my soul, just let me know how I help.

**Comment by darvesh29** [comment]
> @Moo331 I'm a beginner and ready to burn my soul, just let me know how I help.

i think his issue has been resolved

**Comment by rohitchouhan35** [comment]
Still searching for some beginner-friendly open issues that I can contribute to 
can anyone help?

**Comment by Higgs32584** [comment]
@rohitchouhan35 I cannot help you; I am trying to get my first open-source contribution. Issues so poorly explained as this should not be labeled good first issue, as any beginner is likely not familiar enough with the codebase to solve this. I recommend looking for a different issue or project. If anything, do not look at tags for good first issues, but look at issues something that are clearly explained and have a clearly defined problem. Also do not bother looking at issues older than a year, as they are likely not worth pursuing anymore.


I am trying to get my first open-source contribution as well. The one project I found to be easy to set up a dev environment for is matplotlib, maybe you should try that

**Comment by Higgs32584** [comment]
@rohitchouhan35, might I suggest adding to the documentation of a project? Documentation is far easier to contribute to the first time than the code base and still contributes to open source. I still need to complete my first contribution, but I plan to make it documentation.

A first contribution to a codebase is challenging, as one has to know the ins and outs of a massive project to get it approved. Still, documentation is mainly about ease of use, which is far easier for a beginner to see than an expert. I recommend looking through requests for documentation on the matplotlib repo and seeing if you can contribute in any way.

People, in general, are also not good at marking things good first issues, so just look through all of them and go from there.



https://github.com/matplotlib/matplotlib/issues

**Comment by rohitchouhan35** [comment]
@Higgs32584 well said, I'll definitely look for documentation so that I start contributing at least, and thanks for matplotlib recommendation.

**Comment by vimalJD** [comment]
### **Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".**

**Comment by lisad** [comment]
This isn't on anybody's backlog right now, shutterfly or any volunteer's
