### ISSUE TITLE
Keep track of import/export state better

### ISSUE THREAD

**Issue by seehamrun** [dtinit/data-transfer-project#274]
Sometimes we might have a leftover export auth information cookie (from previous attempts), and that causes us to be in import mode during the oauth callback. Which causes us to use the import auth provider to validate export credentials from the callback. 

Example: export msft contacts -> google contacts. After going through msft oauth flow, a leftover cookie from a previous attempt causes us to think this callback is from the import service (google) which leads to attempting to validate the msft token with the google auth generator. Resulting in the following error: 

```
Caused by: com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
 "error" : "invalid_grant",
 "error_description" : "Malformed auth code."
}

```
https://github.com/google/data-transfer-project/blob/49c99ad988afeba659d93bff14b8e0727f2e63f6/portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/ReferenceApiUtils.java#L175

We can do a few things: 
- tie a cookie to a specific job (which should already be implemented in the encrypted flow) 
- store the state in the job and determine state based on that and not based on cookies. 

Temp workaround is to clear cookies before each DTP

**Comment by lisad** [comment]
Siham says this can be closed for now - it's probably specific to the demo API
