### ISSUE TITLE
Istio for retry/timeout policies (and more?)

### ISSUE THREAD

**Issue by rtannenbaum** [dtinit/data-transfer-project#309]
Istio is a platform to manage and secure microservices, and works with Kubernetes.

It provides “service proxying” functionality by running a sidecar container along with each application container, to proxy each request with several configurable features. One of them is retry policies.

For DTP we will need failure/retry logic for all of our communication with service provider APIs. We should hold off on building our own retry logic until we evaluate Istio, as it provides configurable retry logic (per service) and many other features that may be useful to us, especially as DTP evolves/scales.

Istio seems to be used mainly for configuring communication between your own various Istio microservices, but according to https://istio.io/docs/tasks/traffic-management/egress.html they do support communication with external services and you can apply the same routing rules (including retry policies) towards external services (https://istio.io/docs/tasks/traffic-management/egress.html#setting-route-rules-on-an-external-service).

**Comment by calumcalder** [comment]
Istio is deployment-specific, so could be reasonable to add to cloud extensions - `ConnectionProvider` could route requests through the Istio proxy, for example. If someone deploys on top of Istio and wants to contribute the extension I think it would be welcome, but I'll close this issue for now as there doesn't seem to be demand.
Also, I think the ship has sailed on writing our own retry logic 🙂
