### ISSUE TITLE
IMAP support feature request

### ISSUE THREAD

**Issue by holachuy** [dtinit/data-transfer-project#333]
Example code in this gist https://gist.github.com/holachuy/2c28ae6c85045bc45adffaea3192c9a6

Based on previous code here https://github.com/google/data-transfer-project/blob/master/portability-core/src/main/java/org/dataportabilityproject/serviceProviders/common/mail/ImapMailHelper.java

**Comment by lisad** [comment]
While an intriguing possibility, how to get and store and use the user's password seems problematic. OAuth scopes for IMAP access are being worked on in IETF so that's possibly relevant.  In any case, in the meantime this is clearly not planned for implementation on anybody's current work list.
