### ISSUE TITLE
Google Gmail Importer tests

### ISSUE THREAD

**Issue by seehamrun** [dtinit/data-transfer-project#363]

**Comment by ryuzaki-yagami** [comment]
i would like to contribute for this project. Can you guys help me out on how to start and proceed with this issue ?

**Comment by ryuzaki-yagami** [comment]
Can someone help me out ???

**Comment by seehamrun** [comment]
Hi! Thanks for helping out! 

The Gmail importer and exporter live under [extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/mail](https://github.com/google/data-transfer-project/tree/master/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/mail)

We have some minimal tests under [extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mail](https://github.com/google/data-transfer-project/tree/master/extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mail)

A good place to start is reading through the makeup of our [adapter plug in model](https://github.com/google/data-transfer-project/blob/master/Documentation/Overview.md#adapter-plugin-model) to understand how these pieces fit together. Feel free to add onto the test from there (looks like there are a couple of TODOs left in the code).

**Comment by holachuy** [comment]
Hi,

The best place to start is the Developer documentation and get a local environment running:
https://github.com/google/data-transfer-project/blob/master/Documentation/Developer.md


As far as an existing example for an importer test, please see:
https://github.com/google/data-transfer-project/blob/master/extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/contacts/GoogleContactsImporterTest.java

We don't have a general test guidelines doc yet and would welcome any contribution you would like to make towards documentation if you are so inclined.

Here is a general guideline from the Google Testing Blog that may be helpful
https://testing.googleblog.com/2008/08/by-miko-hevery-so-you-decided-to.html

**Comment by ryuzaki-yagami** [comment]
Thank you guys for your response.
I am going through the codebase now. It might take time to start but definitely do it.
Once again thank you guys.

**Comment by holachuy** [comment]
We have some general documentation here about API keys. Let us know if there is anything that is unclear https://github.com/google/data-transfer-project/blob/master/Documentation/Keys.md

**Comment by chandramoulirajagopalan** [comment]
I tried running the dtp using docker-image when I use the localhost link I am not able to authenticate using API keys it says 
401. That’s an error.
Error: invalid_client
The OAuth client was not found.
I get this when I try to run it locally.

**Comment by seehamrun** [comment]
Hi, this happens if the API key/secret are misconfigured. Which service are you getting the error for? Please double check that the client ID and secret that are configured on the service, match what you are passing in the secrets file.

**Comment by chandramoulirajagopalan** [comment]
Google API keys. I get the key id but how to get the secret key. I am confused on how to choose the required API for the concerned application. Can you just help me out.

**Comment by chandramoulirajagopalan** [comment]
Yes now it all works. I guess documentation lacks few information about OAuth registration.

**Comment by cedricvanrompay** [comment]
When creating an OAuth client, what do you put for "authorized domain" if your DTP instance runs on your laptop's `localhost`?

**Comment by cedricvanrompay** [comment]
Ok, well turns out you can put whatever domain you want and you still get OAuth credentials.

Also, I don't know why it's written *“cedricvanrompay unassigned olsona 4 hours ago”*.
Really bad bug from GitHub ?..

**Comment by AlenJoseph55** [comment]
Hey, Can I do the TODO's in the code?

**Comment by bhupal9032** [comment]
i would like to fix this issue.

**Comment by anishlukk123** [comment]
@bhupal. you can work on this

**Comment by jaymasiwal** [comment]
hi, I would like to fix this issue as I've very little prior experience with open source can you please help me out with it

**Comment by EdmondLee958** [comment]
Hello me and my teammate will be working on this issue.

**Comment by Olab23** [comment]
I would like to contribute for this project. Can you guys help me out on how to start and proceed with this issue ?

**Comment by Olab23** [comment]
I would like to contribute for this project. Can you guys help me out on how to start and proceed with this issue ?

**Comment by Klinkaaraa** [comment]
Hello all is there any issue to fix. If so I would like to work on it. Can u guys suggest me??

**Comment by deepakchouhandc** [comment]
I want to support and fix this issue but I don't know who to start.

**Comment by vimalJD** [comment]
**_Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue"._**

**Comment by DumitruDruta** [comment]
Hello, I want to contribute to this issue. Is it still relevant?

**Comment by Klinkaaraa** [comment]
Yes sir.

**Comment by calumcalder** [comment]
There's a single test and more could be added, but since `GoogleMailImporter` has not changed in 5 years I don't think this relevant any more.
