### ISSUE TITLE
Support adding a serialization layer for each veritical

### ISSUE THREAD

**Issue by bwillard** [dtinit/data-transfer-project#404]
Instead of transfering data directly to a new service users might want to be able to move all their data to bloby storage somewhere, e.g. dropbox/GoogleDrive/OneDrive/Perkeep(#307)

The way to do that is probibly to support a serialization plugin per data model that can turn on the one the wire representation into a static representation and then then took the output of that up to any of the providers in the (yet to be built out) bloby storage vertical.

**Comment by lindner** [comment]
Let us Perkeep folks know when you'd like to tackle this.

Also note that Perkeep is more than just blob storage, it can handle full on data models.

**Comment by lisad** [comment]
This isn't currently planned - it's a good idea if it gets to the top of anybody's prioritization list, but it just isn't a top priority right now.
