### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by rtannenbaum** [dtinit/data-transfer-project#43]

**Comment by rtannenbaum** [comment]
With the influx of new collaborators, I think it's important to get this implemented so we don't break our demo image.

Now that we have the awesome new demo server/image, I think it would be good to use it for our integration tests, and run some requests against it.

One option would be to use something like Selenium to execute the OAuth flow in a browser. We'd probably have to (securely) store creds or cookies to log a test user into a browser session for an export and import service.

**Comment by joelhandwell** [comment]
@rtannenbaum you might already know but in case you missed https://www.testcontainers.org can be good candidate to for integration test runner.

**Comment by Kradirhamik** [comment]
I would suggest using Puppeteer + Jest.

**Comment by FranciscoBastos** [comment]
Hi,

My colleague Ana Rita and I are students at masters in software engineering at FEUP (https://paginas.fe.up.pt/~estudar/mesw/). As part of evaluating one of the curriculum units, we need to choose an open-source project and fix an issue. We would like to know if we could help with this issue?

**Comment by igmtz** [comment]
Hello! Is someone currently working on this issue? I would like to contribute!

**Comment by XxBrezxX** [comment]
I'm also looking for a Good First Issue, if this issue is active I'm in

**Comment by vimalJD** [comment]
### **Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".**

**Comment by bengoh815** [comment]
Hey @rtannenbaum, I noticed this issue from 2018 and there has not been much activity or responses. Is this still something that needs to be addressed, or has it been resolved elsewhere?

**Comment by lisad** [comment]
While integration tests for the sample UI and the endpoints might be useful, this issue is too general to be actionable -- nor is it a good first issue.
