### ISSUE TITLE
Add support for task priorities

### ISSUE THREAD

**Issue by olsona** [dtinit/data-transfer-project#430]

**Comment by dineshraj01** [comment]
There is no description on this one. A little help?

**Comment by Washdil** [comment]
please give some description about this

**Comment by indra057** [comment]
hey is this issue fixed can you assign me ..and give me little description about it

**Comment by sachinnandan** [comment]
Hey I would like to work on this. Can I get started

**Comment by bhupal9032** [comment]
i would like to work on this issue and get it done.

**Comment by rkverma2001** [comment]
I would like to work on this issue.

**Comment by pankaj-pilkhwal** [comment]
Please provide some description of the issue.

**Comment by manthanindane** [comment]
Hey Anyone working on this issue....if not, I am ready to help....and also please provide some description about it

**Comment by Moo331** [comment]
Ok go ahead

**Comment by vimalJD** [comment]
Is this project is ongoing let me know further (DOCS) to contribute on it?

**Comment by lisad** [comment]
We've never gotten enough clarity on this task for it to be open to new contributors to actually do; closing as unplanned for now.
