### ISSUE TITLE
Get DTP running on AWS

### ISSUE THREAD

**Issue by rtannenbaum** [dtinit/data-transfer-project#487]

**Comment by dondre** [comment]
What exactly is your issue with running this on Amazon? 
Is the Docker deployment instructions not enough?

I suggest reading this article.
https://aws.amazon.com/getting-started/tutorials/deploy-docker-containers/

**Comment by rtannenbaum** [comment]
Hi @dondre thanks for the comment. To clarify, I meant support for running DTP in production on AWS, where you would want things like secure storage of application credentials using the appropriate services on AWS, and orchestration such as Kubernetes.

See our implementations for GCP and Azure for examples, I think the GCP one is the most production ready at the moment, and stores app keys in Google Cloud Storage, app secrets encrypted via cloud KMS, and orchestration with GKE.

Here's the GCP impl:
https://github.com/google/data-transfer-project/tree/8fbeadf3ef7ac47d489abac1c9862d300d9a89b6/extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google

**Comment by Gulsonish** [comment]
Hi @rtannenbaum , is this problem solved??

**Comment by Gulsonish** [comment]
And, I think S3 and IAM role will be helpful for secure storage of application credentials of DTP in AWS. I think I can implement it but for that need to explore the connected files and need some time.

**Comment by rtannenbaum** [comment]
Hi, I'm no longer working on this project so I’ll pass this along to @seehamrun

**Comment by lisad** [comment]
This isn't  anybody's high priority right now so closing not planned for now.
