### ISSUE TITLE
Add RosCMS support

### ISSUE THREAD

**Issue by erkinalp** [dtinit/data-transfer-project#493]
RosCMS is ReactOS content management system.
Corresponding issue: https://jira.reactos.org/browse/ONLINE-808

**Comment by akuckartz** [comment]
?

**Comment by calumcalder** [comment]
Adding support for a service (either to export or import) typically requires the engagement of the service owners. Looking at the corresponding issue, it was marked as wontfix by ReactOS. I also don't think the data in RosCMS maps well to an existing vertical supported by DTP, so this would be a significant effort.
Going to close this out for now, but if ReactOS change their mind this could be reopened.
