### ISSUE TITLE
Implement Amazon Transfer Extension

### ISSUE THREAD

**Issue by seehamrun** [dtinit/data-transfer-project#744]
https://developer.amazon.com/docs/amazon-drive/ad-restful-api.html

They have a drive API maybe they have one specifically for photos as well?

**Comment by gpriess** [comment]
I looked into implementing this a little while back, and got blocked by the switch to an invite-only API. I wonder if Amazon has plans to open the API to the public?

According to their [Drive API docs](https://developer.amazon.com/docs/amazon-drive/ad-developer-guide.html):

> With our updated RESTful API and SDKs for Android and iOS, Amazon Drive is moving to an invite-only developer offering to ensure we can provide a consistently viable service available for supported use-cases. We want you to be successful when developing apps on the Amazon Drive platform. We have created a guide to help you on your way from getting started to having your app reviewed by our team before releasing it to the public.

**Comment by sorianog** [comment]
Been looking at AWS Upload stuff recently and would love to pick up more Amazon related work on the side. I'd be interested in partnering up with someone to get this going! 😄

**Comment by YashasviChaurasia** [comment]
@sorianog @seehamrun I would like to work on this issue

**Comment by sachinnandan** [comment]
Hey I would like to work on this. Can I get started

**Comment by rkverma2001** [comment]
Hey, I would like to contribute to this issue. Can I get started?

**Comment by vijaymehrotra** [comment]
i would like to contribute in this issue

**Comment by vimalJD** [comment]
### **Is this issue of the project currently running?** 

- It would be great to work with you, I am an enthusiastic to connect with the implementation on amazon transfer extension.
- As I thought there might be used in some **Microservices** to resolve the **small glitches or change request or response** to fix the bugs or minor crashes.
- which connects some centralize repo as working under some controller in **_Java as Spring Framework or Spring boot_** with updated version.

=================================================================================
**I am able to contribute on some tasks using below Tech stacks things Or those would not be used in projects, I can connect ease with the new one Tech stacks**

- Controller or Services relied on some **_design patterns to perform well optimize solution._**
- Also some quick context to get ready with **Web services** under the project to load data with session state by using **_SOAP API and REST API._**
- To resolve with the best conclusion with some environment setup **_API as Postman' data file as yaml can use in another container as Docker._**
- To enable with **_Swagger 2 in a Spring REST API Using Springfox_**
- Or working in xml file with URL mapping **_customize file or Web Framework as ORM_**
- On regarding data or file transfer which is not coming under **_"Entity Framework Core"_** Instead we can use the **_API provided by MongoDB or Cassandra_** as a key-value database.

**Comment by peeyush14goyal** [comment]
As per the [link](https://developer.amazon.com/docs/amazon-drive/ad-restful-api.html) attached, Amazon Drive is deprecated, is this issue still tracked?

**Comment by lisad** [comment]
thanks for raising, I think this issue can be archived.  If anybody has a path forward in the future, we can always resurrect the issue or create a new one.
